language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh

script:
  - qmake -r
  - make
  - make check
